version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: rodhy
      POSTGRES_PASSWORD: secretPassw0rd
      POSTGRES_DB: ecommerce
    ports:
      - "5434:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./data:/data
      - ./infra-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: