# Define the data sources 
sources:
  - name: ecommerce_airflow_etl
    tables:
      - name: orders
      - name: products
      - name: customers
      - name: order_items
      - name: geolocation
      - name: order_payments
      - name: order_reviews
      - name: sellers
